### ISSUE TITLE
suggestions

### ISSUE THREAD

**Issue by paul-hammant** [glfmn/glitter#30]
Title: "A git repository status pretty-printer, for displaying information about your repository in your shell prompt", could be better as "A pretty bash prompt that shows the git repository status for the current directory"

Bash only?  Should be **explicit** with notes for Zsh and Windows/Powershell even if they are not supported.

**Comment by paul-hammant** [comment]
Also glit (as a command) seems secondary to this tech as a bach-promt. In the readme, you should present it as secondary or an "also" thing.

**Comment by glfmn** [comment]
Thank you for pointing out this oversight!  It really helps me understand where my issues and oversights lie in communicating what this project is.  To clarify:

- `glit` was developed to replace [bash-git-prompt] so I have focused on BASH
- I would like `glit` itself to be cross-platform
- Other platforms have not been explicitly supported in the past but I am looking into this

What prompt are you currently using so I can explore support for that platform?

[bash-git-prompt]: https://github.com/magicmonty/bash-git-prompt

**Comment by glfmn** [comment]
> Also glit (as a command) seems secondary to this tech as a bash-prompt. In the readme, you should present it as secondary or an "also" thing.

To clarify on this point as well, `glit` does 3 things:

- `glit` reads the git repository using libgit2 to get the branch, upstream, modified files, etc
- `glit` parses its format language into an AST
- `glit` interprets that AST and injects it with information from the git repository to produce the output

The only reason a shell script is necessary is to actually automatically run the program and put its output in the variable that the shell prompt reads when it presents the prompt.

Color support is done through ANSI escape codes, and the only Bash specific part so far is the option to output special escapes to prevent line wrapping issues in BASH (`-b` flag).  *In theory,* as long as the platform supports ANSI escape codes, then it is 100% supported as long as the user writes a custom script.

Again, thank you for asking these questions and making these suggestions!

**Comment by paul-hammant** [comment]
keep up the good work:)

**Comment by glfmn** [comment]
See #33 

Addressed your suggestions in the latest release.
